apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-default
spec:
  ingressClassName: nginx
  defaultBackend: # Specifies the default backend to handle requests that do not match any defined rules in the Ingress.
                  # Typically, the defaultBackend is used to provide a default error page or a generic service in case of no matching routing rules.
                  # A typical example: Show a "404 - Page Not Found" page.
    service:
      name: nginx
      port: 
        number: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webcolor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # This annotation instructs the NGINX controller to rewrite the URL path to / before forwarding the request to the backend service. This is useful so that backend services do not need to handle full paths.
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx # Indicates that the NGINX controller will manage this Ingress.
  tls:
    - hosts:
      - labdevops.online
      secretName: letsencrypt-prod
  rules:
    - host: labdevops.online # Add domain
      http: # Defines HTTP-based routing rules
        paths: # Route /blue: Requests made to <Ingress-IP>/blue are forwarded to the service service-webcolor-blue on port 80.
          - path: /blue # Requests with paths starting with /blue will be routed to the specified service.
            pathType: Prefix # Indicates that the path should match a prefix in the URL.
            backend:
              service:
                name: service-webcolor-blue # The traffic will be forwarded to the service named service-webcolor-blue
                port: 
                  number: 80
          - path: /green # Route /green: Requests made to <Ingress-IP>/green are forwarded to the service service-webcolor-green on port 80.
            pathType: Prefix
            backend:
              service:
                name: service-webcolor-green
                port: 
                  number: 80